#!/usr/bin/env python3
"""Build hooklist.json (the machine-readable registry) and HOOKS.md (the human
catalog) from every hooks/*.json.

hooklist.json is what aeon.fun/hooks consumes: one array of hook entries, aeon
fleet first (in ship date order) then community, each enriched with the derived
`flagBits` and `callbacks` so the site does not recompute them. The AeonFee that
every aeon hook inherits is emitted once at the top.

Usage:
  python3 scripts/aggregate.py           # (re)write hooklist.json + HOOKS.md
  python3 scripts/aggregate.py --check   # fail if either is stale (CI guard)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hooklib as hl

HOOKLIST_PATH = os.path.join(hl.REPO_ROOT, "hooklist.json")
CATALOG_PATH = os.path.join(hl.REPO_ROOT, "HOOKS.md")

AEON_FEE = {"bps": 10, "recipient": "0xF1E958db7D1e4C074377946018Ad645db4FB158e"}


def enrich(hook):
    bits = int(hook["flags"], 16)
    out = dict(hook)
    out["flagBits"] = bits
    out["callbacks"] = hl.callbacks_of(bits)
    out.setdefault("auditUrl", "")
    return out


def build_hooks():
    hooks = [hl.load_hook(p) for p in hl.hook_paths()]
    # aeon fleet first (ship order), then community (ship order); stable by date+name.
    hooks.sort(key=lambda h: (0 if h["source"] == "aeon" else 1, h["date"], h["name"]))
    return [enrich(h) for h in hooks]


def build_registry(hooks, chains):
    return {
        "name": "aeon univ4 hook list",
        "aeonFee": AEON_FEE,
        "chains": chains,
        "count": len(hooks),
        "verifiedCount": sum(1 for h in hooks if h["verified"]),
        "communityCount": sum(1 for h in hooks if h["source"] == "community"),
        "hooks": hooks,
    }


def build_catalog(hooks, chains):
    lines = [
        "<!-- GENERATED by scripts/aggregate.py from hooks/*.json - do not edit by hand. -->",
        "# Hook catalog",
        "",
        f"{len(hooks)} hooks - "
        f"{sum(1 for h in hooks if h['source'] == 'aeon')} aeon fleet, "
        f"{sum(1 for h in hooks if h['source'] == 'community')} community. "
        "Most aeon hooks inherit the mandatory 10 bps `AeonFee`; a few beforeSwap-only gates take no fee. Regenerate with "
        "`python3 scripts/aggregate.py`.",
        "",
    ]
    for src, title in (("aeon", "aeon fleet"), ("community", "Community submissions")):
        group = [h for h in hooks if h["source"] == src]
        if not group:
            continue
        lines += [f"## {title}", "", "| Hook | Category | Flags | Chains | What it does |", "|------|----------|-------|--------|--------------|"]
        for h in group:
            deployed = " ".join(
                f"[{chains[c]['name']}]({chains[c]['explorer']}/address/{a})"
                for c, a in h["addresses"].items()
                if c in chains
            )
            mech = h["mechanic"].replace("|", "\\|")
            lines.append(f"| {h['name']} | {h['category']} | `{h['flags']}` | {deployed} | {mech} |")
        lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    chains = hl.load_chains()
    hooks = build_hooks()
    registry = json.dumps(build_registry(hooks, chains), indent=2) + "\n"
    catalog = build_catalog(hooks, chains) + "\n"

    if check:
        stale = []
        for path, want in ((HOOKLIST_PATH, registry), (CATALOG_PATH, catalog)):
            have = open(path).read() if os.path.exists(path) else None
            if have != want:
                stale.append(os.path.relpath(path, hl.REPO_ROOT))
        if stale:
            print("STALE: " + ", ".join(stale) + " - run `python3 scripts/aggregate.py`.")
            sys.exit(1)
        print(f"OK: hooklist.json + HOOKS.md are up to date ({len(hooks)} hooks).")
        return

    with open(HOOKLIST_PATH, "w") as f:
        f.write(registry)
    with open(CATALOG_PATH, "w") as f:
        f.write(catalog)
    print(f"Wrote hooklist.json + HOOKS.md ({len(hooks)} hooks).")


if __name__ == "__main__":
    main()
